name: CI

"on":
  workflow_call:
  push:
    branches:
      - main
  pull_request:

env:
  UV_VERSION: "0.11.x"
  UV_MANAGED_PYTHON: "1"

jobs:
  commitlint:
    uses: tcjennings/actions-workflows/.github/workflows/commitlint.yaml@main
    with:
      verbose: true

  lint:
    needs: commitlint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nicegui-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # 7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run Linters
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece  # v3.0.0

      - name: Type check with mypy
        run: uv run --with "nicegui==${{ matrix.nicegui-version }}.*" --isolated mypy -p nice_dialogs

  test-matrix:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
        nicegui-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # 7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --group dev

      - name: Install NiceGUI
        run: uv pip install "nicegui==${{ matrix.nicegui-version }}.*"

      - name: Run tests
        run: uv run pytest

  test:
    needs: test-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Test Matrix Passed
        run: echo "Testing Matrix has passed."
